sudo: false

language: scala
jdk:
  - oraclejdk8
scala:
  - 2.12.6
  - 2.11.12
  - 2.13.0-M4

env:
  - SBT_TASK=core/test
  - SBT_TASK=docs/tut

matrix:
  exclude:
  - scala: 2.13.0-M4
    env: SBT_TASK=docs/tut
  include:
  - scala: 2.12.6
    jdk: oraclejdk10
    env: SBT_TASK=core/test

script:
  - sbt ++$TRAVIS_SCALA_VERSION $SBT_TASK

  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" -delete
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
